In [1]:
a = 1
b = 2

for i in range(10):
    print(a,b)

1 2
1 2
1 2
1 2
1 2
1 2
1 2
1 2
1 2
1 2

# My heading 1
- list of bullets
- more bullets
$$ x*y

In [6]:
print(a - b)
print(a + b)

8
12

In [5]:
a = 10

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [3]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
9             4.9          3.1           1.5          0.1     Setosa
10            5.4          3.7           1.5          0.2     Setosa
11            4.8          3.4           1.6          0.2     Setosa
12            4.8          3.0           1.4          0.1     Setosa
13            4.3          3.0           1.1          0.1     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
16            5.4          3.9           1.3          0.4     Setosa
17            5.1          3.5           1.4          0.3     Setosa
18            5.7          3.8           1.7          0.3     Setosa
19            5.1          3.8           1.5          0.3     Setosa
20            5.4          3.4           1.7          0.2     Setosa
21            5.1          3.7           1.5          0.4     Setosa
22            4.6          3.6           1.0          0.2     Setosa
23            5.1          3.3           1.7          0.5     Setosa
24            4.8          3.4           1.9          0.2     Setosa
25            5.0          3.0           1.6          0.2     Setosa
26            5.0          3.4           1.6          0.4     Setosa
27            5.2          3.5           1.5          0.2     Setosa
28            5.2          3.4           1.4          0.2     Setosa
29            4.7          3.2           1.6          0.2     Setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [6]:
df['variety']

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
5         Setosa
6         Setosa
7         Setosa
8         Setosa
9         Setosa
10        Setosa
11        Setosa
12        Setosa
13        Setosa
14        Setosa
15        Setosa
16        Setosa
17        Setosa
18        Setosa
19        Setosa
20        Setosa
21        Setosa
22        Setosa
23        Setosa
24        Setosa
25        Setosa
26        Setosa
27        Setosa
28        Setosa
29        Setosa
         ...
120    Virginica
121    Virginica
122    Virginica
123    Virginica
124    Virginica
125    Virginica
126    Virginica
127    Virginica
128    Virginica
129    Virginica
130    Virginica
131    Virginica
132    Virginica
133    Virginica
134    Virginica
135    Virginica
136    Virginica
137    Virginica
138    Virginica
139    Virginica
140    Virginica
141    Virginica
142    Virginica
143    Virginica
144    Virginica
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [9]:
df[['petal.length', 'variety']]

     petal.length    variety
0             1.4     Setosa
1             1.4     Setosa
2             1.3     Setosa
3             1.5     Setosa
4             1.4     Setosa
5             1.7     Setosa
6             1.4     Setosa
7             1.5     Setosa
8             1.4     Setosa
9             1.5     Setosa
10            1.5     Setosa
11            1.6     Setosa
12            1.4     Setosa
13            1.1     Setosa
14            1.2     Setosa
15            1.5     Setosa
16            1.3     Setosa
17            1.4     Setosa
18            1.7     Setosa
19            1.5     Setosa
20            1.7     Setosa
21            1.5     Setosa
22            1.0     Setosa
23            1.7     Setosa
24            1.9     Setosa
25            1.6     Setosa
26            1.6     Setosa
27            1.5     Setosa
28            1.4     Setosa
29            1.6     Setosa
..            ...        ...
120           5.7  Virginica
121           4.9  Virginica
122           6.7  Virginica
123           4.9  Virginica
124           5.7  Virginica
125           6.0  Virginica
126           4.8  Virginica
127           4.9  Virginica
128           5.6  Virginica
129           5.8  Virginica
130           6.1  Virginica
131           6.4  Virginica
132           5.6  Virginica
133           5.1  Virginica
134           5.6  Virginica
135           6.1  Virginica
136           5.6  Virginica
137           5.5  Virginica
138           4.8  Virginica
139           5.4  Virginica
140           5.6  Virginica
141           5.1  Virginica
142           5.1  Virginica
143           5.9  Virginica
144           5.7  Virginica
145           5.2  Virginica
146           5.0  Virginica
147           5.2  Virginica
148           5.4  Virginica
149           5.1  Virginica

[150 rows x 2 columns]

In [11]:
df[2:6]

   sepal.length  sepal.width  petal.length  petal.width variety
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa

In [12]:
df[['petal.length', 'variety']][2:6]

   petal.length variety
2           1.3  Setosa
3           1.5  Setosa
4           1.4  Setosa
5           1.7  Setosa